import type { DistrictImage } from "@/lib/types";

/**
 * A photograph for every district, keyed by district id.
 *
 * All 25 are freely licensed files from Wikimedia Commons, chosen to show a
 * place a resident of that district would recognise — the town centre, the
 * coast or the landmark — rather than a stock weather picture. Every URL was
 * fetched and confirmed to return an image before being written down here.
 *
 * `credit` and `license` are not decoration: most of these are CC BY-SA, which
 * requires the photographer to be named wherever the photo is shown. The card
 * renders them, so do not drop the fields when adding a district.
 *
 * The width and height are the real pixel size of the file served at the URL.
 * next/image needs both to hold space for the photo while it loads, which is
 * what stops the board jumping around as the grid fills in.
 */
export const DISTRICT_IMAGES: Record<string, DistrictImage> = {
  "colombo": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Colombo_city_skyline_at_night.png/1280px-Colombo_city_skyline_at_night.png",
    width: 1280,
    height: 960,
    alt: "The Colombo high-rise skyline lit up at night",
    credit: "Gihanud2001",
    license: "CC0",
    source: "https://commons.wikimedia.org/wiki/File:Colombo_city_skyline_at_night.png",
  },
  "gampaha": {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Gampaha_Town.jpg",
    width: 1280,
    height: 912,
    alt: "Shophouses and traffic along the main street of Gampaha town",
    credit: "Wikiceylon.pvt",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Gampaha_Town.jpg",
  },
  "kalutara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Aerial_view_of_Kalutara_City%2C_Sri_Lanka.jpg/1280px-Aerial_view_of_Kalutara_City%2C_Sri_Lanka.jpg",
    width: 1280,
    height: 914,
    alt: "Aerial view of Kalutara, with the Kalu Ganga meeting the sea",
    credit: "Brayan.87622",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Kalutara_City,_Sri_Lanka.jpg",
  },
  "kandy": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/SL_Kandy_asv2020-01_img33_Sacred_Tooth_Temple.jpg/1280px-SL_Kandy_asv2020-01_img33_Sacred_Tooth_Temple.jpg",
    width: 1280,
    height: 640,
    alt: "The Temple of the Sacred Tooth Relic beside Kandy Lake",
    credit: "A.Savin",
    license: "FAL",
    source: "https://commons.wikimedia.org/wiki/File:SL_Kandy_asv2020-01_img33_Sacred_Tooth_Temple.jpg",
  },
  "matale": {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f5/City_of_Matale.jpg",
    width: 1280,
    height: 962,
    alt: "Rooftops of Matale town below the surrounding hills",
    credit: "Yoyohoney",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:City_of_Matale.jpg",
  },
  "nuwara-eliya": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/NuwaraEliya_from_top.jpg/1280px-NuwaraEliya_from_top.jpg",
    width: 1280,
    height: 960,
    alt: "Nuwara Eliya seen from the hills above the town",
    credit: "Abdul malik77",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:NuwaraEliya_from_top.jpg",
  },
  "galle": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Galle_Fort.jpg/1280px-Galle_Fort.jpg",
    width: 1280,
    height: 959,
    alt: "The ramparts of Galle Fort on the headland",
    credit: "Rovin Shanila",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Galle_Fort.jpg",
  },
  "matara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Matara_Fort_clock_tower.jpg/1280px-Matara_Fort_clock_tower.jpg",
    width: 1280,
    height: 852,
    alt: "The clock tower inside Matara Fort",
    credit: "Dan arndt",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Matara_Fort_clock_tower.jpg",
  },
  "hambantota": {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/06/Hambantota_Administrative_Complex.jpg",
    width: 1280,
    height: 961,
    alt: "The Hambantota district administrative complex",
    credit: "Deneth17",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Hambantota_Administrative_Complex.jpg",
  },
  "jaffna": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Jaffna_Public_Library.jpg/1280px-Jaffna_Public_Library.jpg",
    width: 1280,
    height: 824,
    alt: "The white colonnaded facade of Jaffna Public Library",
    credit: "Thamizhpparithi Maari",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Jaffna_Public_Library.jpg",
  },
  "kilinochchi": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kilinochchi_Railway_Station_-_Sri_Lanka.jpg/1280px-Kilinochchi_Railway_Station_-_Sri_Lanka.jpg",
    width: 1280,
    height: 960,
    alt: "Kilinochchi railway station",
    credit: "Rehman Abubakr",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kilinochchi_Railway_Station_-_Sri_Lanka.jpg",
  },
  "mannar": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Lighthouse%2C_Talaimannar.jpg/1280px-Lighthouse%2C_Talaimannar.jpg",
    width: 1280,
    height: 960,
    alt: "The lighthouse at Talaimannar on the Mannar coast",
    credit: "Adam Jones",
    license: "CC BY-SA 2.0",
    source: "https://commons.wikimedia.org/wiki/File:Lighthouse,_Talaimannar.jpg",
  },
  "vavuniya": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Vavuniya_City.jpg/1280px-Vavuniya_City.jpg",
    width: 1280,
    height: 721,
    alt: "The centre of Vavuniya town",
    credit: "Vaijayanth",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Vavuniya_City.jpg",
  },
  "mullaitivu": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Mullaitivu_district_secretariat_building.jpg",
    width: 1280,
    height: 960,
    alt: "The Mullaitivu district secretariat building",
    credit: "Mahimsan",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mullaitivu_district_secretariat_building.jpg",
  },
  "batticaloa": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Sea_Fishing%2C_Batticaloa.jpg/1280px-Sea_Fishing%2C_Batticaloa.jpg",
    width: 1280,
    height: 897,
    alt: "Fishermen working the sea off Batticaloa",
    credit: "Anton Croos",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sea_Fishing,_Batticaloa.jpg",
  },
  "ampara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Ampara.jpg/1280px-Ampara.jpg",
    width: 1280,
    height: 960,
    alt: "A tank and open country in Ampara",
    credit: "Frantishak",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Ampara.jpg",
  },
  "trincomalee": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Bay_of_Trincomalee.jpg/1280px-Bay_of_Trincomalee.jpg",
    width: 1280,
    height: 852,
    alt: "The bay at Trincomalee",
    credit: "Kondephy",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bay_of_Trincomalee.jpg",
  },
  "kurunegala": {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Kurunegala_City_from_the_Sky.jpg",
    width: 1280,
    height: 1600,
    alt: "Kurunegala town seen from the air below Athugala rock",
    credit: "Sandaruwan Rajapaksha 2003",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kurunegala_City_from_the_Sky.jpg",
  },
  "puttalam": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Sri_Lanka%2C_Puttalam_street_scene_%285%29.jpg/1280px-Sri_Lanka%2C_Puttalam_street_scene_%285%29.jpg",
    width: 1280,
    height: 850,
    alt: "A street scene in Puttalam town",
    credit: "Vincent van Zeijst",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sri_Lanka,_Puttalam_street_scene_(5).jpg",
  },
  "anuradhapura": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Ruwanweli_Maha_Saaya.jpg/1280px-Ruwanweli_Maha_Saaya.jpg",
    width: 1280,
    height: 960,
    alt: "The Ruwanweli Maha Seya stupa at Anuradhapura",
    credit: "Thisaru Tharuka",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ruwanweli_Maha_Saaya.jpg",
  },
  "polonnaruwa": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Polonnaruwa_01.jpg/1280px-Polonnaruwa_01.jpg",
    width: 1280,
    height: 888,
    alt: "The ancient ruins at Polonnaruwa",
    credit: "Bernard Gagnon",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Polonnaruwa_01.jpg",
  },
  "badulla": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Badulla_Clock_Tower.JPG/1280px-Badulla_Clock_Tower.JPG",
    width: 1280,
    height: 1707,
    alt: "The Badulla clock tower",
    credit: "L Manju",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Badulla_Clock_Tower.JPG",
  },
  "monaragala": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Monaragala_Viharaya.jpg/1280px-Monaragala_Viharaya.jpg",
    width: 1280,
    height: 960,
    alt: "The temple at Monaragala below the rock",
    credit: "Hiruzara",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Monaragala_Viharaya.jpg",
  },
  "ratnapura": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Ratnapura_Clock_Tower.jpg/1280px-Ratnapura_Clock_Tower.jpg",
    width: 1280,
    height: 1707,
    alt: "The Ratnapura clock tower",
    credit: "L Manju",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ratnapura_Clock_Tower.jpg",
  },
  "kegalle": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/97/Kegalle_Town_Clock_Tower.jpg",
    width: 1280,
    height: 1707,
    alt: "The clock tower in the centre of Kegalle town",
    credit: "Uvindus",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Kegalle_Town_Clock_Tower.jpg",
  },
};
